export const data = [
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "XS",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["White"],
      "Component_Price": "800",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "XS",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["Yellow"],
      "Component_Price": "900",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "XS",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["Rose"],
      "Component_Price": "921",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "XS",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["White" , "Yellow"],
      "Component_Price": "924",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "XS",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["White" , "Rose"],
      "Component_Price": "875",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "XS",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["White" , "Yellow"],
      "Component_Price": "356",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "XS",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["White" , "Yellow"],
      "Component_Price": "365",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "XS",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["Rose" , "White"],
      "Component_Price": "467",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "XS",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["Rose" , "Yellow"],
      "Component_Price": "575",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "S",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["White"],
      "Component_Price": "987",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "S",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["Yellow"],
      "Component_Price": "876",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "S",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["Rose"],
      "Component_Price": "765",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "S",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["White" , "Yellow"],
      "Component_Price": "145",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "S",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["Rose" , "White"],
      "Component_Price": "142",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "S",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["White" , "Yellow"],
      "Component_Price": "1543",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "S",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["Rose" , "Yellow"],
      "Component_Price": "123",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "S",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["Rose" , "White"],
      "Component_Price": "450",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    },
    {
      "COMPONENT_SKU": "",
      "STYLE": "Script_01",
      "Letter": "A",
      "SIZE": "S",
      "STONE_TYPE": "Moissanite",
      "Metal_Type": "Silver",
      "Metal_Color": ["Rose" , "Yellow"],
      "Component_Price": "120",
      "Approx_Ctw": "",
      "Approx_Gram": "",
      "Approx_Stone": "",
      "Approx_Width": ""
    }
  ]